# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Integración continua sobre el módulo es_primo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configurar Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Comprobación de código con pylint
      run: |
        # falla la integración si la puntuación (score) del linting es menor al umbral indicado
        pylint --fail-under=10 src
        
    - name: Pruebas con pytest
      run: |
        pytest
